db:
  configs:
    cronjob:
      connMaxIdleTime: 600s
      connMaxLifetime: 1800s
      driverName: pgx
      dsn: host=localhost port=5432 user=postgres password=postgres dbname=vibeme sslmode=disable
      maxIdleConns: 5
      maxOpenConns: 20
      pingTimeout: 5s
    job:
      connMaxIdleTime: 600s
      connMaxLifetime: 1800s
      driverName: pgx
      dsn: host=localhost port=5432 user=postgres password=postgres dbname=vibeme sslmode=disable
      maxIdleConns: 5
      maxOpenConns: 20
      pingTimeout: 5s
redis:
  configs:
    cronjob:
      addrs:
      - localhost:6379
      password: "123456"
    job:
      addrs:
      - localhost:6379
      password: "123456"
