apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.grpc }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.grpc }}
spec:
  replicas: {{ .Values.replicaCount.grpc }}
  selector:
    matchLabels:
      app: {{ .Values.app.grpc }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.grpc }}
    spec:
      containers:
      - name: {{ .Values.app.grpc }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/app/app"]
        args: ["grpc"]
        ports:
        - containerPort: {{ .Values.grpc.port }} 
          name: grpc
        - containerPort: {{ .Values.grpc.httpPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ .Values.nacos.configMap }}
        env:
        - name: ENV
          value: "{{ .Values.env.env }}"
        - name: GRPC_PORT
          value: "{{ .Values.grpc.port }}"
        - name: HTTP_PORT
          value: "{{ .Values.grpc.httpPort }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels.app
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.grpc.resources | indent 10 }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.grpc.port }}
          initialDelaySeconds: {{ .Values.grpc.probes.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.grpc.probes.startup.periodSeconds }}
          failureThreshold: {{ .Values.grpc.probes.startup.failureThreshold }}
          successThreshold: {{ .Values.grpc.probes.startup.successThreshold }}
        livenessProbe:
          grpc:
            port: {{ .Values.grpc.port }}
          initialDelaySeconds: {{ .Values.grpc.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.grpc.probes.liveness.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.grpc.port }}
          initialDelaySeconds: {{ .Values.grpc.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.grpc.probes.readiness.periodSeconds }}
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.grpc }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.grpc }}
spec:
  selector:
    app: {{ .Values.app.grpc }}
  ports:
    - protocol: TCP
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      name: grpc
    - protocol: TCP
      port: {{ .Values.grpc.httpPort }}
      targetPort: {{ .Values.grpc.httpPort }}
      name: http
  type: ClusterIP