apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.http }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.http }}
spec:
  replicas: {{ .Values.replicaCount.http }}
  selector:
    matchLabels:
      app: {{ .Values.app.http }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.http }}
    spec:
      containers:
      - name: {{ .Values.app.http }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/app/app"]
        args: ["http"]
        ports:
        - containerPort: {{ .Values.http.port }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ .Values.nacos.configMap }}
        env:
        - name: ENV
          value: "{{ .Values.env.env }}"
        - name: HTTP_PORT
          value: "{{ .Values.http.port }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels.app
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.http.resources | indent 10 }}
        startupProbe:
          httpGet:
            path: /startz
            port: {{ .Values.http.port }}
          initialDelaySeconds: {{ .Values.http.probes.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.http.probes.startup.periodSeconds }}
          failureThreshold: {{ .Values.http.probes.startup.failureThreshold }}
          successThreshold: {{ .Values.http.probes.startup.successThreshold }}
        livenessProbe:
          httpGet:
            path: /livez
            port: {{ .Values.http.port }}
          initialDelaySeconds: {{ .Values.http.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.http.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.http.port }}
          initialDelaySeconds: {{ .Values.http.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.http.probes.readiness.periodSeconds }}
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.http }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.http }}
spec:
  selector:
    app: {{ .Values.app.http }}
  ports:
    - protocol: TCP
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
      name: http
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.http }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: grocer-http.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.http }}-service
            port:
              number: {{ .Values.http.port }}