apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nacos.configMap }}
  namespace: {{ .Values.namespace }}
data:
  NACOS_CONFIG_IP: "{{ .Values.nacos.config.ip }}"
  NACOS_CONFIG_PORT: "{{ .Values.nacos.config.port }}"
  NACOS_CONFIG_NAMESPACE: "{{ .Values.nacos.config.namespace }}"
  NACOS_CONFIG_GROUP: "{{ .Values.nacos.config.group }}"
  NACOS_CONFIG_DATA_ID: "{{ .Values.nacos.config.dataId }}"