# Common configuration
namespace: default

image:
  repository: docker.io/grocer
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

env:
  env: production

nacos:
  configMap: nacos-config
  config:
    ip: "127.0.0.1"
    port: "8848"
    namespace: "public"
    group: "DEFAULT_GROUP"
    dataId: "vibeme-micro.yaml"
